# Generated by Django 5.2.16 on 2026-09-15 18:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.core.validators.validate_adult_birth_date]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', validators=[apps.core.validators.validate_image_file], verbose_name='Photo of Member'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[apps.core.validators.validate_nid_number], verbose_name='National ID (NID)'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='nid_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/nid/', validators=[apps.core.validators.validate_image_file], verbose_name='Photo of NID'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='nominee_nid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[apps.core.validators.validate_nid_number]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='nominee_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.core.validators.validate_bd_phone]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='nominee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/nominees/', validators=[apps.core.validators.validate_image_file], verbose_name='Photo of Nominee'),
        ),
    ]
