# Generated by Django 5.2.16 on 2026-09-15 18:10

import apps.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loaninstallment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantor_nid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[apps.core.validators.validate_nid_number]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantor_phone',
            field=models.CharField(max_length=20, validators=[apps.core.validators.validate_bd_phone]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.core.validators.validate_positive_amount]),
        ),
        migrations.AlterField(
            model_name='loanscheme',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, validators=[apps.core.validators.validate_positive_amount]),
        ),
        migrations.AlterField(
            model_name='loanscheme',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12, validators=[apps.core.validators.validate_positive_amount]),
        ),
    ]
